wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.31
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.19
    t:
      4: 3.9.19
      5: 0.10.31
      8:
      - 5
input_artifact:
  desc: null
  value: data_to_be_cleaned:v0
output_artifact:
  desc: null
  value: clean_data
output_description:
  desc: null
  value: '''clean dataset'''
output_type:
  desc: null
  value: dataset
